<a href="https://colab.research.google.com/github/faruqbusiness07/Machine-Learning/blob/main/Machine%20Learning%20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

IMPORT LIBRARY

In [ ]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

import matplotlib.pyplot as plt

Upload File

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving Ai (Responses) (1).xlsx to Ai (Responses) (1).xlsx

Excel nya

In [ ]:
df = pd.read_excel("Ai (Responses) (1).xlsx")

df.head()

,Timestamp,Jenis Kelamin,Program Studi,Asal Universitas,Semester Saat Ini,Apakah Anda mengikuti organisasi atau kegiatan kampus?,Apakah Anda pernah mengikuti organisasi atau kegiatan kampus sebelumnya?,Apakah ajakan teman mempengaruhi keputusan Anda mengikuti kegiatan kampus?,Apakah Anda memiliki waktu luang untuk mengikuti kegiatan kampus di luar jam kuliah?,"Jika ada kegiatan kampus yang sesuai minat Anda dalam waktu dekat, apakah Anda akan hadir?"
0,2026-06-05 10:14:20.052,Laki-laki,Teknik Informatika,Universitas Duta Bangsa Surakarta,4,Tidak,Tidak,Berpengaruh,Ya,Hadir
1,2026-06-05 10:28:45.903,Laki-laki,Teknik Informatika,Universitas Duta Bangsa,4,Ikut,Ya,Tidak,Ya,Tidak Hadir
2,2026-06-05 11:24:05.917,Perempuan,Teknik Informatika,universitas duta bangsa,4,Tidak,Tidak,Tidak,Tidak,Hadir
3,2026-06-05 11:33:19.513,Laki-laki,Teknik Informatika,UDB,4,Tidak,Tidak,Tidak,Tidak,Hadir
4,2026-06-05 11:40:48.988,Laki-laki,Hubungan Internasional,Universitas Slamet Riyadi,6,Ikut,Tidak,Berpengaruh,Ya,Hadir

Cek nama kolom

In [ ]:
df.columns

Index(['Timestamp', 'Jenis Kelamin ', '  Program Studi  ', 'Asal Universitas',
       '  Semester Saat Ini  ',
       'Apakah Anda mengikuti organisasi atau kegiatan kampus?',
       ' Apakah Anda pernah mengikuti organisasi atau kegiatan kampus sebelumnya?  ',
       ' Apakah ajakan teman mempengaruhi keputusan Anda mengikuti kegiatan kampus?  ',
       'Apakah Anda memiliki waktu luang untuk mengikuti kegiatan kampus di luar jam kuliah? ',
       ' Jika ada kegiatan kampus yang sesuai minat Anda dalam waktu dekat, apakah Anda akan hadir?  '],
      dtype='object')

In [ ]:
df.columns = df.columns.str.strip()

df.columns

Index(['Timestamp', 'Jenis Kelamin', 'Program Studi', 'Asal Universitas',
       'Semester Saat Ini',
       'Apakah Anda mengikuti organisasi atau kegiatan kampus?',
       'Apakah Anda pernah mengikuti organisasi atau kegiatan kampus sebelumnya?',
       'Apakah ajakan teman mempengaruhi keputusan Anda mengikuti kegiatan kampus?',
       'Apakah Anda memiliki waktu luang untuk mengikuti kegiatan kampus di luar jam kuliah?',
       'Jika ada kegiatan kampus yang sesuai minat Anda dalam waktu dekat, apakah Anda akan hadir?'],
      dtype='object')

Ambil kolom yg dipakai

In [ ]:
data = df[[
    'Apakah Anda mengikuti organisasi atau kegiatan kampus?',
    'Apakah Anda pernah mengikuti organisasi atau kegiatan kampus sebelumnya?',
    'Apakah ajakan teman mempengaruhi keputusan Anda mengikuti kegiatan kampus?',
    'Apakah Anda memiliki waktu luang untuk mengikuti kegiatan kampus di luar jam kuliah?',
    'Jika ada kegiatan kampus yang sesuai minat Anda dalam waktu dekat, apakah Anda akan hadir?'
]]

data.head()

,Apakah Anda mengikuti organisasi atau kegiatan kampus?,Apakah Anda pernah mengikuti organisasi atau kegiatan kampus sebelumnya?,Apakah ajakan teman mempengaruhi keputusan Anda mengikuti kegiatan kampus?,Apakah Anda memiliki waktu luang untuk mengikuti kegiatan kampus di luar jam kuliah?,"Jika ada kegiatan kampus yang sesuai minat Anda dalam waktu dekat, apakah Anda akan hadir?"
0,Tidak,Tidak,Berpengaruh,Ya,Hadir
1,Ikut,Ya,Tidak,Ya,Tidak Hadir
2,Tidak,Tidak,Tidak,Tidak,Hadir
3,Tidak,Tidak,Tidak,Tidak,Hadir
4,Ikut,Tidak,Berpengaruh,Ya,Hadir

Cek jumlah korespomden

In [ ]:
print("Jumlah responden:", len(data))

Jumlah responden: 321

cek output koresponden hadir/tdk hadir

In [ ]:
data.iloc[:,4].value_counts()

Jika ada kegiatan kampus yang sesuai minat Anda dalam waktu dekat, apakah Anda akan hadir?
Hadir          219
Tidak Hadir    102
Name: count, dtype: int64

ubah teks menjadi angka endcoding

In [ ]:
from sklearn.preprocessing import LabelEncoder

data_encoded = data.copy()

for col in data_encoded.columns:
    le = LabelEncoder()
    data_encoded[col] = le.fit_transform(data_encoded[col])

data_encoded.head()

,Apakah Anda mengikuti organisasi atau kegiatan kampus?,Apakah Anda pernah mengikuti organisasi atau kegiatan kampus sebelumnya?,Apakah ajakan teman mempengaruhi keputusan Anda mengikuti kegiatan kampus?,Apakah Anda memiliki waktu luang untuk mengikuti kegiatan kampus di luar jam kuliah?,"Jika ada kegiatan kampus yang sesuai minat Anda dalam waktu dekat, apakah Anda akan hadir?"
0,1,0,0,1,0
1,0,1,1,1,1
2,1,0,1,0,0
3,1,0,1,0,0
4,0,0,0,1,0

pisah input dan output

In [ ]:
X = data_encoded.iloc[:,0:4]

y = data_encoded.iloc[:,4]

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (321, 4)
y shape: (321,)

split data

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Data Training:", len(X_train))
print("Data Testing:", len(X_test))

Data Training: 256
Data Testing: 65

Random Forest

In [ ]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

model.fit(X_train, y_train)

print("Model berhasil dilatih")

Model berhasil dilatih

Cek akurasi

In [ ]:
from sklearn.metrics import accuracy_score

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

print("Akurasi Model:", round(accuracy*100,2), "%")

Akurasi Model: 81.54 %

Confusion Matriks

In [ ]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

print(cm)

[[43  6]
 [ 6 10]]

Faktor yg berpengaruh

In [ ]:
feature_names = X.columns

importance = model.feature_importances_

for nama, nilai in zip(feature_names, importance):
    print(nama, ":", round(nilai,3))

Apakah Anda mengikuti organisasi atau kegiatan kampus? : 0.291
Apakah Anda pernah mengikuti organisasi atau kegiatan kampus sebelumnya? : 0.135
Apakah ajakan teman mempengaruhi keputusan Anda mengikuti kegiatan kampus? : 0.159
Apakah Anda memiliki waktu luang untuk mengikuti kegiatan kampus di luar jam kuliah? : 0.414

Presentasi LK Pr

In [ ]:
gender_percent = (df['Jenis Kelamin']
                  .value_counts(normalize=True)*100)

print(gender_percent.round(2))

Jenis Kelamin
Laki-laki    54.21
Perempuan    45.79
Name: proportion, dtype: float64

kelompok LK yg pernah berorganisasi

In [ ]:
laki = df[df['Jenis Kelamin'] == 'Laki-laki']

persen_org_laki = (
    laki['Apakah Anda pernah mengikuti organisasi atau kegiatan kampus sebelumnya?']
    .value_counts(normalize=True)*100
)

print(persen_org_laki.round(2))

Apakah Anda pernah mengikuti organisasi atau kegiatan kampus sebelumnya?
Ya       52.3
Tidak    47.7
Name: proportion, dtype: float64

kelompok LK brp yg akan hadir

In [ ]:
hadir_laki = (
    laki['Jika ada kegiatan kampus yang sesuai minat Anda dalam waktu dekat, apakah Anda akan hadir?']
    .value_counts(normalize=True)*100
)

print(hadir_laki.round(2))

Jika ada kegiatan kampus yang sesuai minat Anda dalam waktu dekat, apakah Anda akan hadir?
Hadir          67.24
Tidak Hadir    32.76
Name: proportion, dtype: float64